### ISSUE TITLE
Sveriges statskalender 

### ISSUE THREAD

**Issue by salgo60** [salgo60/Wikidata_riksdagen-corpus#36]
## Bra källa [Sveriges statskalender](http://runeberg.org/statskal/1877/0096.html) 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/14206509/154751268-f4afeeac-bc97-4178-9d41-159ff05bc513.png">

* Runeberg 1877 - 1954 http://runeberg.org/statskal/ - fritextsökning och enskild sida kan länkas
    *  1877 Riksdagen [sida 73](http://runeberg.org/statskal/1877/0096.html)
      * exempel referens 
         * Wikidata  [Q6047693#P1343](https://www.wikidata.org/wiki/Q6047693#P1343)
         * Wikipedia [Adolph Peyron](https://sv.wikipedia.org/wiki/Adolph_Peyron)
 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/14206509/154138672-1b81baeb-4a88-4914-9688-a029eb208f5d.png">
     
<img width="612" alt="image" src="https://user-images.githubusercontent.com/14206509/154138387-09c0c302-36a8-4541-9c45-53f8597ca825.png">

* Sveriges statskalender finns även hos [Gbg](https://gupea.ub.gu.se/handle/2077/68175/browse?type=dateissued&submit_browse=Issue+Date)  1880-2010 men verkar inte möjligt att länka direkt till sida...

* [SPARQL](https://w.wiki/4qzi) har källa "[Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) / Q58366813" 
   * samma SPARQL men [med bild](https://w.wiki/4rKs) / [utan bild](https://w.wiki/4rKt)
   * samma SPARQL men [karta med plats född](https://w.wiki/4qfP) plus länk Riksarkivet SBL/SKBL om artikel finns

<img width="386" alt="image" src="https://user-images.githubusercontent.com/14206509/154157100-6fb2f3b9-cadc-40df-826a-2a357f408487.png">

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/14206509/154157053-576782bd-47f7-4f35-a160-1ce90e454456.png">

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/14206509/154208345-8cda45cf-6974-487e-96e4-63d382ff3fe6.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/14206509/154676996-a58694fa-b9b6-4047-9eb3-fa8d125cd566.png">

see also [Add statskalender and personregister data to our personregister #122](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/122) would be good **if we could help each other with data quality**

## Maintenance queries ##
* has source [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) [but miss "I Riksdagen kallad"](https://w.wiki/4qv3) / [has "I Riksdagen kallad"](https://w.wiki/4qum)
* has source [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) but miss source [Tvåkammar-riksdagen 1867-1970](https://www.wikidata.org/wiki/Q110346241) --> [SPARQL](https://w.wiki/4qv8)
* has source [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) page 73-78 --> should be 328?!?!? records  (page 72 =  42, page 73 =  63, page 74 = 55, page 75 = 44, page 76 = 51, page 77 = 46, page 78 = 26 --> 328)
   * [SPARQL](https://w.wiki/4r3G)    
## Misc ##
* people with source [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) buried on Nothern Cemetery in Stockholm regarding to Wikidata -> [SPARQL](https://w.wiki/4qxv)
   * same query but for all cemeteries --> [SPARQL](https://query.wikidata.org/embed.html#%23defaultView%3AMap%7B%20%22markercluster%22%3A%20%7B%22maxClusterRadius%22%3A%2070%7D%7D%0A%23title%3A%20people%20mentioned%20in%20Sveriges%20statskalender%201877%20as%20part%20of%20the%20Swedish%20PM%20in%20Wikidata%20and%20have%20a%20coordinate%20on%20a%20grave%0Aselect%20distinct%20%20%3Farticle%20%3Fperson%20%3FpersonLabel%20%20%3FpersonDescription%20%20%3Fgraveplot%20%20%3Fpic%20%3Fcoord%20%3FpicGrave%20%0A%28IRI%28CONCAT%28%22https%3A%2F%2Fwww.google.com%2Fmaps%2F%3Fq%3D%22%2C%20STR%28%3Flat%29%2C%20%22%2C%22%2C%20STR%28%3Flon%29%29%29%20AS%20%3FGoogleMap%29%20%0A%3FnamedAs%20%3Fref%20%3Fpage%20%7B%0A%7B%0A%20%20%20%20%3FsvCemetery%20wdt%3AP31%20wd%3AQ39614.%0A%23%20%20%20%20%3FsvCemetery%20wdt%3AP17%20wd%3AQ34.%0A%0A%20%20%20%20values%20%3Fsource%20%20%7Bwd%3AQ58366813%7D%20%23Sveriges%20statskalender%201877%20%0A%20%20%20%20%3Fperson%20p%3AP1343%20%3FnodeSources.%0A%20%20%20%20%3FnodeSources%20ps%3AP1343%20%20%3Fsource.%0A%20%20%20%20%3FnodeSources%20prov%3AwasDerivedFrom%20%5B%20pr%3AP304%20%3Fpage%20%5D%20%0A%20%20%20%20OPTIONAL%7B%3FnodeSources%20prov%3AwasDerivedFrom%20%5B%20pr%3AP1810%20%3FnamedAs%20%5D%7D%20.%0A%20%20%20%20OPTIONAL%7B%3FnodeSources%20prov%3AwasDerivedFrom%20%5B%20pr%3AP854%20%3Fref%20%5D%7D%20.%0A%0A%09%3Fperson%20wdt%3AP119%20%3FsvCemetery%3B%20%23Place%20of%20burial%0A%20%20%20%20%20%20%20%20%20%20%20%20p%3AP119%20%5B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP625%20%3Fcoord%3B%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pqv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Flat%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Flon%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D.%20%20%20%20%20%0A%0A%20%20%20OPTIONAL%20%7B%3Fperson%20wdt%3AP569%20%3Fbirthdate%7D%20%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP18%20%3Fpic%20.%7D%20%09%09%09%09%09%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP1442%20%3FpicGrave%20.%7D%20%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%7D%20%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%22%2C%22en%22%7D%0A%20%7D%0AOrder%20by%20%3FpersonLabel) "people mentioned in Sveriges statskalender 1877 as part of the Swedish PM in Wikidata and have a coordinate on a grave"
      * all Swedish PMs in Wikidata with coordinate grave [SPARQL](https://w.wiki/4tJ3)
   
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/14206509/154651196-93899be0-04fb-4797-8a89-ed74ffb5bac1.png">
    
* picture grave in Wikidata for a person with name "I riksdagen kallad" - [SPARQL](https://w.wiki/4f6c) 
  * same with source [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) - [SPARQL](https://w.wiki/4rAv)
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/14206509/154651491-a098716b-49c9-41bc-82ea-ede838b01c3b.png">
  
* external properties in Wikidata for people with source [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) - [SPARQL](https://w.wiki/4qx$)

**Comment by salgo60** [comment]
**Lesson learned** Error in [Sveriges statskalender 1877](https://www.wikidata.org/wiki/Q58366813) makes matching difficult

1) Grefve Gustaf Mauritz Posse, Godsegare f. 25; 72. [link](http://runeberg.org/statskal/1877/0097.html)
<img width="641" alt="image" src="https://user-images.githubusercontent.com/14206509/154489544-683d26e7-7508-4f9f-bc8f-d5ec64fcd657.png">

wrong birth date should be **1823** and same as [SBL 7375](https://sok.riksarkivet.se/sbl/Presentation.aspx?id=7375) / WD [Q6054467](http://www.wikidata.org/entity/Q6054467)

**Comment by salgo60** [comment]
**Udda** 
* "Johan Erik Johansson i Forneby, Hemmansegare, f. 25; 75, för Torstuna, Simtuna, Öfver-Tjurbo och Våla domsaga"
     * verkar vara [Johan Emanuel Jansson](https://sv.wikipedia.org/wiki/Johan_Jansson_i_Sax%C3%A5n) samma som [SPA](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABgb-w) 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/14206509/154659243-130a16a3-183e-4292-b0ab-e91fe19d461e.png">
   
<img width="667" alt="image" src="https://user-images.githubusercontent.com/14206509/154660026-33c0a585-b918-4bcf-a078-a5b8edb1b395.png">

**Comment by salgo60** [comment]
**TODO**
* [ ] jmf ovan med sv:WIkipedia listor 
  * [ ] [Lista över ledamöter av Sveriges riksdags första kammare 1879 ](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_f%C3%B6rsta_kammare_1879)
  * [ ] [Lista över ledamöter av Sveriges riksdags andra kammare 1879–1881 ](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1879%E2%80%931881)
* [ ]  add more sources

**Comment by salgo60** [comment]
Andra kandidater

* ["Valstatistik statistiska Centralbyråns rörande Riksdagsmannavalen åren 1891-1893"](https://share.scb.se/ov9993/data/historisk%20statistik/BISOS%201851-1917%2FBISOS%20R%20Valstatistik%201871-1910%2FBISOS%20R%20Riksdagsmannavalen%201872-1908%2FValstatistik-R-Riksdagsmannavalen-1891-1893.pdf)

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/14206509/154980840-7a572416-edcd-441e-a8bb-6649db24952a.png">

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/14206509/154980681-015663fb-3c20-463d-857a-7fd87e79ad53.png">

**Comment by salgo60** [comment]
As pictures are available from SPA [portrattarkiv.se](https://portrattarkiv.se/) then we get some Swedish PM related picture categories they have....

* [Category:Porträttbok: Riksdagsmän 1897](https://commons.wikimedia.org/wiki/Category:Portr%C3%A4ttbok:_Riksdagsm%C3%A4n_1897)

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/14206509/155878477-f46d7caa-0b1f-4d6b-bcc3-4a067fe51b93.png">

see more at [Category:Porträttbok](https://commons.wikimedia.org/wiki/Category:Portr%C3%A4ttbok)
<img width="867" alt="image" src="https://user-images.githubusercontent.com/14206509/155878505-4a855236-bb02-4643-a4a3-bb6fbb8ae419.png">
